### ISSUE TITLE
Add products to shopping cart

### ISSUE THREAD

**Issue by reedse** [reedse/chess-ai#3]
# Add products to shopping cart

As a customer, I want to add products to my shopping cart so that I can purchase multiple items in one transaction.

## Tasks:
- [ ] Implement "Add to Cart" button on the product page (2 points)
- [ ] Store the selected products in the shopping cart session (2 points)
- [ ] Update the cart count dynamically when a product is added (1 point)
