### ISSUE TITLE
Remove items from shopping cart

### ISSUE THREAD

**Issue by reedse** [reedse/chess-ai#4]
# Remove items from shopping cart

As a customer, I want to remove items from my shopping cart so that I don’t have to buy things I no longer want.

## Tasks:
- [ ] Add a "Remove" button next to items in the shopping cart (1 point)
- [ ] Update the cart count when items are removed (1 point)
- [ ] Recalculate total price after removal (2 points)
