### ISSUE TITLE
Receive an email confirmation

### ISSUE THREAD

**Issue by reedse** [reedse/chess-ai#7]
# Receive an email confirmation

As a customer, I want to receive an email confirmation after placing an order so that I can have a record of my purchase.

## Tasks:
- [ ] Set up email service integration (e.g., SMTP, SendGrid) (2 points)
- [ ] Generate order confirmation emails with order details (2 points)
- [ ] Send confirmation email to the customer after order placement (2 points)
